# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    access_control_allow_listener:
        class:  AppBundle\EventListener\AccessControlAllowListener
        tags:
          - { name: kernel.event_listener, event: kernel.response }

    http_options_listener:
        class:  AppBundle\EventListener\HttpOptionsListener
        tags:
          - { name: kernel.event_listener, event: kernel.request, priority: 100 }
