services:
    sonata.admin.visit:
        class: AppBundle\Admin\VisitAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Visites", label: "Visites" }
        arguments:
            - ~
            - AppBundle\Entity\Visit
            - ~

    sonata.admin.user:
        class: AppBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Utilisateurs", label: "Utilisateurs" }
        arguments:
            - ~
            - AppBundle\Entity\User
            - ~

    sonata.admin.message:
        class: AppBundle\Admin\MessageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Visites", label: "Messages" }
        arguments:
            - ~
            - AppBundle\Entity\Message
            - ~
